### ISSUE TITLE
`az aks create` funkar inte enligt senaste instruktionen

### ISSUE THREAD

**Issue by lilja85** [pelithne/techdays2019#5]
Hej,

På workshoppen lyckades jag köra

````
az aks create --resource-group techdays --name <myaks> --disable-rbac --generate-ssh-keys --attach-acr <myacr>
````

Men då skapas en aks nod med 3 instanser av storleken Standard_DS2 v2. Denna käkade upp min subscription på bara några dagar, vilket jag upptäckte jag när jag skulle sitta och labba lite i helgen...

Ni ändrade under workshoppen till
````
az aks create --resource-group techdays --name <myaks> --disable-rbac --generate-ssh-keys --attach-acr <myacr> --load-balancer-sku basic --node-count 1 --node-vm-size Standard_B1s 
````
Men den får jag felmeddelande på när jag försöker köra på konto kopplat till mitt MSDN:
AAD role propagation done[############################################]  100.0000%
Operation failed with status: 'Bad Request'. Details: The VM SKU chosen for this cluster `Standard_B1s` does not have enough CPU/memory to run as an AKS node. Please see https://aka.ms/aks/restricted-skus for more details.

Har du något tips på hur jag kan skapa en AKS som kostar så lite som möjligt men som man fortfarande kan labba med utana att mina MSDN $ tar slut?

**Comment by pelithne** [comment]
Jag vill minnas att jag skapat kluster med B1s tidigare, men det fungerar (som du noterat) i alla fall inte längre. B2s är den minsta SKU som fungerar för AKS. 

Billigast möjliga kluster får du då med: 
az aks create --resource-group techdays --name <myaks> --disable-rbac --generate-ssh-keys --attach-acr <myacr> --load-balancer-sku basic --node-count 1 --node-vm-size Standard_B2s och det borde kosta under 300 SEK i månaden.

**Comment by pelithne** [comment]
Fixed in 23e562e

**Comment by lilja85** [comment]
Ok, ska testa om man kan skapa nytt från början. När jag testade ändra storleken till den du föreslog får jag felmeddelande

````
Failed to update virtual machine scale set 'aks-nodepool1-16397758-vmss'. Error: Virtual machine at index 0 of VM scale set aks-nodepool1-16397758-vmss has size Standard_B2s, which is not compatible with enabling accelerated networking in the network profile on the scale set. Allowed sizes:
````

Går det komma runt detta på något bra sätt?

**Comment by pelithne** [comment]
Det verkar som att du redan har ett kluster? I så fall borde det räcka att ta bort det, och kör kommandot igen.

**Comment by lilja85** [comment]
Ja precis, jag hade hoppats man kunde fixa det som redan fanns men gav upp. När jag testade ta bort aks resursgruppen samt en `Kubernetes Service` från techdays-resursgruppen gick det bra köra `az aks create`. Tack för hjälpen!

Om någon annan läser detta hittade jag följande bloggpost om hur man kan stänga ner sina AKS-noder när man inte använder dem. Jag tänker nog testa sen: https://blog.headforcloud.com/2018/07/17/save-money-on-aks/
